name: 'Crawlora App Publish'
description: 'Publish your crawlora app using GitHub Actions'
author: 'Crawlora <git@crawlora.com>'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  working-directory:
    description: Path where we need to work
    required: false
    default: ./__example_app__
  auth_key:
    description: 'api key from crawlora'
    required: true
    default: 'fake'

runs:
  using: node20
  main: dist/index.js
