name: Test Action Locally

on:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./__example_app__
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        env:
          CRAWLORA_AUTH_KEY: ${{ secrets.CRAWLORA_AUTH_KEY }}
        with:
          working-directory: ./__example_app__
          auth_key: ${{ secrets.CRAWLORA_AUTH_KEY }}
