name: Test Action Locally

on: push

jobs:
  test-action:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./__example_app__
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        env:
          CRAWLORA_AUTH_KEY: 15759d84a019af47798293d0b0b67f0f0bab8b3bf257d1e0b155e2ecb963ce87a24f7a52305b10380d54dfd360f24e3b0e9b8d7e56a289ef20d53004a5e59d95
        with:
          working-directory: ./__example_app__
          auth_key: 15759d84a019af47798293d0b0b67f0f0bab8b3bf257d1e0b155e2ecb963ce87a24f7a52305b10380d54dfd360f24e3b0e9b8d7e56a289ef20d53004a5e59d95
